# [Use Tensorflow DNNClassifier estimator to classify MNIST dataset](https://codeburst.io/use-tensorflow-dnnclassifier-estimator-to-classify-mnist-dataset-a7222bf9f940)

原文很老了，跑出很多 deprecated warning. 分析 150 天行情資料需要用到同樣的技術。

不用再花時間上網重複抓 mnist dataset 只要 copy 那四個 .gz 檔案 

    t10k-images-idx3-ubyte.gz 
    t10k-labels-idx1-ubyte.gz 
    train-images-idx3-ubyte.gz 
    train-labels-idx1-ubyte.gz

到 working directory 之下的 MNIST_data/ 裡去即可 <-- 查出這個位置的方法是，隨便讓它跑一次就會在 working directory 下 created.

In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data
import peforth

In [2]:
%%f  Now we redefine the 'unknown' command that was doing nothing
     : unknown ( token -- thing Y|N) // Try to find the unknown token in __main__
       py> getattr(sys.modules['__main__'],pop(),"Ûnknôwn") 
       py> str(tos())=="Ûnknôwn" if drop false else true then ;
         
     \ here after, when FORTH come accross an unknown token, instead of an error 
     \ message, it try to find the token in python __main__ module name space.

     \ Redefine \ commant to print it 
     code \ print(nexttoken('\n')) end-code 

reDef unknown

Error! Redefine unknown.



In [5]:
# 不用在花時間上網重複抓 mnist dataset 只要 copy 那四個 .gz 檔案 
# t10k-images-idx3-ubyte.gz t10k-labels-idx1-ubyte.gz train-images-idx3-ubyte.gz train-labels-idx1-ubyte.gz
# 到 working directory 之下的 MNIST_data/ 裡去即可。

mnist = input_data.read_data_sets('MNIST_data')

def input(dataset):
    '''
    傳回 mnist.test mnist.train mnist.validation 看哪個 dataset 當中的 (feature,label) 
    '''
    return dataset.images, dataset.labels.astype(np.int32)
    # where dataset is i.e. mnist.test or mnist.train or mnist.validation

'''
mnist :> test.labels[0] type ==> <class 'numpy.uint8'> 要轉成 np.int32
mnist :> test.images.shape   ==> (10000, 784)
mnist :> test.images[0] type ==> <class 'numpy.ndarray'>
mnist :> test.images[0][0] type ==> <class 'numpy.float32'>
'''

Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data\train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data\train-labels-idx1-ubyte.gz
Extracting MNIST_data\t10k-images-idx3-ubyte.gz
Extracting MNIST_data\t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


"\nmnist :> test.labels[0] type ==> <class 'numpy.uint8'> 要轉成 np.int32\nmnist :> test.images.shape   ==> (10000, 784)\nmnist :> test.images[0] type ==> <class 'numpy.ndarray'>\nmnist :> test.images[0][0] type ==> <class 'numpy.float32'>\n"

可參考 GitHub\workshops\notebooks\1-mnist-with-keras.ipynb 看新的怎麼做

    WARNING:tensorflow:From <ipython-input-2-f61e226d87df>:1: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
    Instructions for updating:
    Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
    WARNING:tensorflow:From c:\users\hcche\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
    Instructions for updating:
    Please write your own downloading logic.
    WARNING:tensorflow:From c:\users\hcche\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:252: _internal_retry.<locals>.wrap.<locals>.wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
    Instructions for updating:
    Please use urllib or similar directly.
    Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
    WARNING:tensorflow:From c:\users\hcche\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
    Instructions for updating:
    Please use tf.data to implement this functionality.
    Extracting MNIST_data\train-images-idx3-ubyte.gz
    Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
    WARNING:tensorflow:From c:\users\hcche\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
    Instructions for updating:
    Please use tf.data to implement this functionality.
    Extracting MNIST_data\train-labels-idx1-ubyte.gz
    Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
    Extracting MNIST_data\t10k-images-idx3-ubyte.gz
    Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
    Extracting MNIST_data\t10k-labels-idx1-ubyte.gz
    WARNING:tensorflow:From c:\users\hcche\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
    Instructions for updating:
    Please use alternatives such as official/mnist/dataset.py from tensorflow/models.

In [7]:
# Specify feature
feature_columns = [tf.feature_column.numeric_column("x", shape=[28, 28])]

In [8]:
%%f 查看上面這 feature_columns 啥玩意兒?
tf py> [pop().feature_column.numeric_column("xx",shape=[8,8])] dup . cr \ "xx" 可以亂寫
type . cr 
feature_columns type . cr
\ 這玩意兒應該是 iterator 之類的東西 ==> 錯! 它是個 class
tf :> feature_column.numeric_column("abc",shape=[8,8]) dup ( 留一份 ) type . cr
py> [pop()] . cr \ 把這個 class 放進 [...] 裡去，似乎有點 new 出來的味道，但 "xx" 是亂寫的故不然。

\ 總之，這已經解答了 150 天行情該怎麼表達的問題。答案是:
tf py> [pop().feature_column.numeric_column("day150",shape=[150,5])] dup . cr
\ 比土土的 750 flattend 要有意義。 

[_NumericColumn(key='xx', shape=(8, 8), default_value=None, dtype=tf.float32, normalizer_fn=None)]
<class 'list'>
<class 'list'>
<class 'tensorflow.python.feature_column.feature_column._NumericColumn'>
[_NumericColumn(key='abc', shape=(8, 8), default_value=None, dtype=tf.float32, normalizer_fn=None)]
[_NumericColumn(key='day150', shape=(150, 5), default_value=None, dtype=tf.float32, normalizer_fn=None)]


In [9]:
# Build 2 layer DNN classifier
classifier = tf.estimator.DNNClassifier(
    feature_columns=feature_columns,
    hidden_units=[256, 32],
    optimizer=tf.train.AdamOptimizer(1e-4),
    n_classes=10,
    dropout=0.1,
    model_dir="./tmp/mnist_model"
    )

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './tmp/mnist_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000018731F4A358>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [26]:
%f \ 看清楚等下要用的 x y 啥東西
x = {"x": input(mnist.train)[0]}
y = input(mnist.train)[1]
%f x :> ['x'].shape tib.
%f x :> ['x'][:4] tib.
%f y :> shape tib.
%f y :> [:10] . cr
    

x :> ['x'].shape tib. \ ==> (55000, 784) (<class 'tuple'>)
x :> ['x'][:4] tib. \ ==> [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] (<class 'numpy.ndarray'>)
y :> shape tib. \ ==> (55000,) (<class 'tuple'>)
[7 3 4 6 1 8 1 0 9 8]


In [11]:
# Define the training inputs
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": input(mnist.train)[0]},
    y=input(mnist.train)[1],
    num_epochs=None,
    batch_size=50,
    shuffle=True
    )

In [12]:
classifier.train(input_fn=train_input_fn, steps=100000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into ./tmp/mnist_model\model.ckpt.
INFO:tensorflow:loss = 113.34591, step = 1
INFO:tensorflow:global_step/sec: 360.308
INFO:tensorflow:loss = 85.05225, step = 101 (0.279 sec)
INFO:tensorflow:global_step/sec: 429.876
INFO:tensorflow:loss = 44.792667, step = 201 (0.233 sec)
INFO:tensorflow:global_step/sec: 423.56
INFO:tensorflow:loss = 31.400679, step = 301 (0.235 sec)
INFO:tensorflow:global_step/sec: 389.968
INFO:tensorflow:loss = 36.160217, step = 401 (0.257 sec)
INFO:tensorflow:global_step/sec: 431.718
INFO:tensorflow:loss = 35.42182, step = 501 (0.231 sec)
INFO:tensorflow:global_step/sec: 432.645
INFO:tensorflow:loss = 23.563938, step = 601 (0.232 sec)
INFO:tensorflow:global_step/sec: 429.877
INFO:tensorflow:lo

INFO:tensorflow:global_step/sec: 421.785
INFO:tensorflow:loss = 12.818614, step = 8101 (0.237 sec)
INFO:tensorflow:global_step/sec: 443.105
INFO:tensorflow:loss = 6.2958655, step = 8201 (0.226 sec)
INFO:tensorflow:global_step/sec: 428.053
INFO:tensorflow:loss = 5.400663, step = 8301 (0.234 sec)
INFO:tensorflow:global_step/sec: 442.135
INFO:tensorflow:loss = 10.03683, step = 8401 (0.226 sec)
INFO:tensorflow:global_step/sec: 442.132
INFO:tensorflow:loss = 5.503536, step = 8501 (0.227 sec)
INFO:tensorflow:global_step/sec: 443.107
INFO:tensorflow:loss = 6.7141733, step = 8601 (0.225 sec)
INFO:tensorflow:global_step/sec: 440.202
INFO:tensorflow:loss = 2.5439897, step = 8701 (0.227 sec)
INFO:tensorflow:global_step/sec: 396.096
INFO:tensorflow:loss = 10.827284, step = 8801 (0.253 sec)
INFO:tensorflow:global_step/sec: 436.39
INFO:tensorflow:loss = 6.0135226, step = 8901 (0.229 sec)
INFO:tensorflow:global_step/sec: 439.247
INFO:tensorflow:loss = 10.353671, step = 9001 (0.228 sec)
INFO:tensorflo

INFO:tensorflow:global_step/sec: 382.567
INFO:tensorflow:loss = 3.454037, step = 16401 (0.261 sec)
INFO:tensorflow:global_step/sec: 402.421
INFO:tensorflow:loss = 6.313217, step = 16501 (0.248 sec)
INFO:tensorflow:global_step/sec: 405.66
INFO:tensorflow:loss = 2.2119706, step = 16601 (0.247 sec)
INFO:tensorflow:global_step/sec: 363.923
INFO:tensorflow:loss = 8.018305, step = 16701 (0.275 sec)
INFO:tensorflow:global_step/sec: 404.033
INFO:tensorflow:loss = 1.4589651, step = 16801 (0.248 sec)
INFO:tensorflow:global_step/sec: 404.035
INFO:tensorflow:loss = 4.475649, step = 16901 (0.247 sec)
INFO:tensorflow:global_step/sec: 397.658
INFO:tensorflow:loss = 0.45137516, step = 17001 (0.251 sec)
INFO:tensorflow:global_step/sec: 404.034
INFO:tensorflow:loss = 2.4082103, step = 17101 (0.249 sec)
INFO:tensorflow:global_step/sec: 404.035
INFO:tensorflow:loss = 4.3875155, step = 17201 (0.247 sec)
INFO:tensorflow:global_step/sec: 399.234
INFO:tensorflow:loss = 2.0277011, step = 17301 (0.252 sec)
INFO

INFO:tensorflow:loss = 0.9838403, step = 24601 (0.250 sec)
INFO:tensorflow:global_step/sec: 389.968
INFO:tensorflow:loss = 1.1325042, step = 24701 (0.257 sec)
INFO:tensorflow:global_step/sec: 403.226
INFO:tensorflow:loss = 1.8802344, step = 24801 (0.248 sec)
INFO:tensorflow:global_step/sec: 402.421
INFO:tensorflow:loss = 1.2640308, step = 24901 (0.247 sec)
INFO:tensorflow:global_step/sec: 351.242
INFO:tensorflow:loss = 4.840315, step = 25001 (0.286 sec)
INFO:tensorflow:global_step/sec: 402.421
INFO:tensorflow:loss = 2.8852684, step = 25101 (0.248 sec)
INFO:tensorflow:global_step/sec: 391.481
INFO:tensorflow:loss = 1.6467816, step = 25201 (0.256 sec)
INFO:tensorflow:global_step/sec: 263.203
INFO:tensorflow:loss = 1.2133048, step = 25301 (0.382 sec)
INFO:tensorflow:global_step/sec: 329.433
INFO:tensorflow:loss = 1.1699759, step = 25401 (0.301 sec)
INFO:tensorflow:global_step/sec: 269.536
INFO:tensorflow:loss = 1.2247974, step = 25501 (0.371 sec)
INFO:tensorflow:global_step/sec: 350.022
I

INFO:tensorflow:loss = 5.0618944, step = 32801 (0.284 sec)
INFO:tensorflow:global_step/sec: 367.907
INFO:tensorflow:loss = 0.51276684, step = 32901 (0.273 sec)
INFO:tensorflow:global_step/sec: 391.482
INFO:tensorflow:loss = 0.697296, step = 33001 (0.253 sec)
INFO:tensorflow:global_step/sec: 400.822
INFO:tensorflow:loss = 3.0486875, step = 33101 (0.250 sec)
INFO:tensorflow:global_step/sec: 408.123
INFO:tensorflow:loss = 1.0279503, step = 33201 (0.245 sec)
INFO:tensorflow:global_step/sec: 374.05
INFO:tensorflow:loss = 2.101342, step = 33301 (0.269 sec)
INFO:tensorflow:global_step/sec: 348.811
INFO:tensorflow:loss = 0.57918566, step = 33401 (0.287 sec)
INFO:tensorflow:global_step/sec: 370.611
INFO:tensorflow:loss = 2.5450914, step = 33501 (0.270 sec)
INFO:tensorflow:global_step/sec: 380.404
INFO:tensorflow:loss = 0.34287837, step = 33601 (0.263 sec)
INFO:tensorflow:global_step/sec: 387.717
INFO:tensorflow:loss = 2.9977002, step = 33701 (0.257 sec)
INFO:tensorflow:global_step/sec: 385.493


INFO:tensorflow:global_step/sec: 404.034
INFO:tensorflow:loss = 1.2840874, step = 41101 (0.247 sec)
INFO:tensorflow:global_step/sec: 400.82
INFO:tensorflow:loss = 0.51275325, step = 41201 (0.251 sec)
INFO:tensorflow:global_step/sec: 400.823
INFO:tensorflow:loss = 2.5157812, step = 41301 (0.249 sec)
INFO:tensorflow:global_step/sec: 401.618
INFO:tensorflow:loss = 2.643587, step = 41401 (0.248 sec)
INFO:tensorflow:global_step/sec: 407.299
INFO:tensorflow:loss = 2.6892798, step = 41501 (0.245 sec)
INFO:tensorflow:global_step/sec: 356.839
INFO:tensorflow:loss = 0.26430154, step = 41601 (0.281 sec)
INFO:tensorflow:global_step/sec: 396.876
INFO:tensorflow:loss = 2.7615514, step = 41701 (0.250 sec)
INFO:tensorflow:global_step/sec: 406.477
INFO:tensorflow:loss = 0.35609782, step = 41801 (0.249 sec)
INFO:tensorflow:global_step/sec: 369.256
INFO:tensorflow:loss = 1.1499963, step = 41901 (0.270 sec)
INFO:tensorflow:global_step/sec: 332.694
INFO:tensorflow:loss = 0.84406793, step = 42001 (0.300 sec

INFO:tensorflow:global_step/sec: 398.445
INFO:tensorflow:loss = 0.20820972, step = 49301 (0.253 sec)
INFO:tensorflow:global_step/sec: 407.299
INFO:tensorflow:loss = 0.0775872, step = 49401 (0.247 sec)
INFO:tensorflow:global_step/sec: 384.759
INFO:tensorflow:loss = 0.19073927, step = 49501 (0.257 sec)
INFO:tensorflow:global_step/sec: 405.658
INFO:tensorflow:loss = 0.041567195, step = 49601 (0.247 sec)
INFO:tensorflow:global_step/sec: 393.776
INFO:tensorflow:loss = 0.57969636, step = 49701 (0.255 sec)
INFO:tensorflow:global_step/sec: 400.027
INFO:tensorflow:loss = 0.054228768, step = 49801 (0.249 sec)
INFO:tensorflow:global_step/sec: 360.022
INFO:tensorflow:loss = 0.4086367, step = 49901 (0.279 sec)
INFO:tensorflow:global_step/sec: 393.776
INFO:tensorflow:loss = 0.70179987, step = 50001 (0.252 sec)
INFO:tensorflow:global_step/sec: 393.008
INFO:tensorflow:loss = 0.24234271, step = 50101 (0.256 sec)
INFO:tensorflow:global_step/sec: 400.82
INFO:tensorflow:loss = 0.1376651, step = 50201 (0.2

INFO:tensorflow:global_step/sec: 342.879
INFO:tensorflow:loss = 0.48469383, step = 57501 (0.293 sec)
INFO:tensorflow:global_step/sec: 386.23
INFO:tensorflow:loss = 0.11194462, step = 57601 (0.259 sec)
INFO:tensorflow:global_step/sec: 397.66
INFO:tensorflow:loss = 0.07861644, step = 57701 (0.251 sec)
INFO:tensorflow:global_step/sec: 388.465
INFO:tensorflow:loss = 1.615509, step = 57801 (0.257 sec)
INFO:tensorflow:global_step/sec: 407.299
INFO:tensorflow:loss = 0.20410675, step = 57901 (0.246 sec)
INFO:tensorflow:global_step/sec: 384.024
INFO:tensorflow:loss = 1.0505316, step = 58001 (0.260 sec)
INFO:tensorflow:global_step/sec: 389.214
INFO:tensorflow:loss = 0.29160088, step = 58101 (0.257 sec)
INFO:tensorflow:global_step/sec: 371.981
INFO:tensorflow:loss = 0.3453249, step = 58201 (0.270 sec)
INFO:tensorflow:global_step/sec: 361.313
INFO:tensorflow:loss = 0.09122456, step = 58301 (0.275 sec)
INFO:tensorflow:global_step/sec: 395.319
INFO:tensorflow:loss = 0.94651496, step = 58401 (0.252 s

INFO:tensorflow:global_step/sec: 369.932
INFO:tensorflow:loss = 0.07997502, step = 65701 (0.271 sec)
INFO:tensorflow:global_step/sec: 351.243
INFO:tensorflow:loss = 0.075700685, step = 65801 (0.284 sec)
INFO:tensorflow:global_step/sec: 399.233
INFO:tensorflow:loss = 0.017113587, step = 65901 (0.250 sec)
INFO:tensorflow:global_step/sec: 404.032
INFO:tensorflow:loss = 0.14574675, step = 66001 (0.248 sec)
INFO:tensorflow:global_step/sec: 396.098
INFO:tensorflow:loss = 1.6495866, step = 66101 (0.252 sec)
INFO:tensorflow:global_step/sec: 393.776
INFO:tensorflow:loss = 0.7017714, step = 66201 (0.254 sec)
INFO:tensorflow:global_step/sec: 371.294
INFO:tensorflow:loss = 0.38830867, step = 66301 (0.269 sec)
INFO:tensorflow:global_step/sec: 394.546
INFO:tensorflow:loss = 1.5139508, step = 66401 (0.253 sec)
INFO:tensorflow:global_step/sec: 367.238
INFO:tensorflow:loss = 0.07274285, step = 66501 (0.273 sec)
INFO:tensorflow:global_step/sec: 371.979
INFO:tensorflow:loss = 0.18568853, step = 66601 (0.

INFO:tensorflow:loss = 0.6953699, step = 73801 (0.258 sec)
INFO:tensorflow:global_step/sec: 389.965
INFO:tensorflow:loss = 0.07710338, step = 73901 (0.256 sec)
INFO:tensorflow:global_step/sec: 396.877
INFO:tensorflow:loss = 0.8792875, step = 74001 (0.252 sec)
INFO:tensorflow:global_step/sec: 356.837
INFO:tensorflow:loss = 0.067210436, step = 74101 (0.282 sec)
INFO:tensorflow:global_step/sec: 392.244
INFO:tensorflow:loss = 0.035250753, step = 74201 (0.252 sec)
INFO:tensorflow:global_step/sec: 407.297
INFO:tensorflow:loss = 0.14726953, step = 74301 (0.246 sec)
INFO:tensorflow:global_step/sec: 395.322
INFO:tensorflow:loss = 0.9349474, step = 74401 (0.254 sec)
INFO:tensorflow:global_step/sec: 403.226
INFO:tensorflow:loss = 0.014068702, step = 74501 (0.248 sec)
INFO:tensorflow:global_step/sec: 397.658
INFO:tensorflow:loss = 1.0161912, step = 74601 (0.252 sec)
INFO:tensorflow:global_step/sec: 383.296
INFO:tensorflow:loss = 0.13162175, step = 74701 (0.260 sec)
INFO:tensorflow:global_step/sec:

INFO:tensorflow:global_step/sec: 378.261
INFO:tensorflow:loss = 1.5819316, step = 82001 (0.262 sec)
INFO:tensorflow:global_step/sec: 375.443
INFO:tensorflow:loss = 0.298057, step = 82101 (0.268 sec)
INFO:tensorflow:global_step/sec: 354.329
INFO:tensorflow:loss = 0.02416439, step = 82201 (0.282 sec)
INFO:tensorflow:global_step/sec: 382.565
INFO:tensorflow:loss = 0.04196376, step = 82301 (0.261 sec)
INFO:tensorflow:global_step/sec: 405.661
INFO:tensorflow:loss = 0.034629237, step = 82401 (0.247 sec)
INFO:tensorflow:global_step/sec: 387.717
INFO:tensorflow:loss = 0.04803078, step = 82501 (0.258 sec)
INFO:tensorflow:global_step/sec: 409.782
INFO:tensorflow:loss = 0.11287938, step = 82601 (0.243 sec)
INFO:tensorflow:global_step/sec: 398.446
INFO:tensorflow:loss = 0.07476175, step = 82701 (0.251 sec)
INFO:tensorflow:global_step/sec: 404.033
INFO:tensorflow:loss = 0.2022398, step = 82801 (0.247 sec)
INFO:tensorflow:global_step/sec: 402.422
INFO:tensorflow:loss = 1.011973, step = 82901 (0.250 

INFO:tensorflow:loss = 0.12568639, step = 90101 (0.264 sec)
INFO:tensorflow:global_step/sec: 395.32
INFO:tensorflow:loss = 2.0888186, step = 90201 (0.252 sec)
INFO:tensorflow:global_step/sec: 393.007
INFO:tensorflow:loss = 0.26527864, step = 90301 (0.256 sec)
INFO:tensorflow:global_step/sec: 393.776
INFO:tensorflow:loss = 0.0370504, step = 90401 (0.263 sec)
INFO:tensorflow:global_step/sec: 365.149
INFO:tensorflow:loss = 0.17112145, step = 90501 (0.266 sec)
INFO:tensorflow:global_step/sec: 354.329
INFO:tensorflow:loss = 0.04281682, step = 90601 (0.280 sec)
INFO:tensorflow:global_step/sec: 384.024
INFO:tensorflow:loss = 0.2721407, step = 90701 (0.260 sec)
INFO:tensorflow:global_step/sec: 401.62
INFO:tensorflow:loss = 0.050296348, step = 90801 (0.249 sec)
INFO:tensorflow:global_step/sec: 389.967
INFO:tensorflow:loss = 0.11664173, step = 90901 (0.256 sec)
INFO:tensorflow:global_step/sec: 393.008
INFO:tensorflow:loss = 0.1608204, step = 91001 (0.255 sec)
INFO:tensorflow:global_step/sec: 396

INFO:tensorflow:loss = 0.24762693, step = 98201 (0.285 sec)
INFO:tensorflow:global_step/sec: 341.714
INFO:tensorflow:loss = 0.016810043, step = 98301 (0.292 sec)
INFO:tensorflow:global_step/sec: 405.664
INFO:tensorflow:loss = 0.032149017, step = 98401 (0.245 sec)
INFO:tensorflow:global_step/sec: 403.226
INFO:tensorflow:loss = 0.025139986, step = 98501 (0.248 sec)
INFO:tensorflow:global_step/sec: 404.845
INFO:tensorflow:loss = 0.0156931, step = 98601 (0.248 sec)
INFO:tensorflow:global_step/sec: 398.445
INFO:tensorflow:loss = 0.0061006295, step = 98701 (0.251 sec)
INFO:tensorflow:global_step/sec: 403.226
INFO:tensorflow:loss = 0.011047589, step = 98801 (0.248 sec)
INFO:tensorflow:global_step/sec: 402.421
INFO:tensorflow:loss = 0.31707093, step = 98901 (0.248 sec)
INFO:tensorflow:global_step/sec: 376.846
INFO:tensorflow:loss = 0.007137699, step = 99001 (0.268 sec)
INFO:tensorflow:global_step/sec: 363.921
INFO:tensorflow:loss = 0.025858447, step = 99101 (0.274 sec)
INFO:tensorflow:global_s

In [13]:
%f \ 看清楚等下要用的 x y 啥東西
x = {"x": input(mnist.test)[0]}
y = input(mnist.test)[1]
%f x :> ['x'].shape tib.
%f y :> shape tib.
%f x :> ['x'][:4] tib.

x :> ['x'].shape tib. \ ==> (10000, 784) (<class 'tuple'>)
y :> shape tib. \ ==> (10000,) (<class 'tuple'>)
x :> ['x'][:4] tib. \ ==> [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] (<class 'numpy.ndarray'>)


In [14]:
# Define the test inputs
test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": input(mnist.test)[0]},
    y=input(mnist.test)[1],
    num_epochs=1,
    shuffle=False
    )

In [15]:
# Evaluate accuracy
accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]
print("\nTest Accuracy: {0:f}%\n".format(accuracy_score*100))

# End of "mnist_estimator.py"


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-06-03-01:46:47
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./tmp/mnist_model\model.ckpt-100000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2018-06-03-01:46:48
INFO:tensorflow:Saving dict for global step 100000: accuracy = 0.9836, average_loss = 0.08139293, global_step = 100000, loss = 10.302903

Test Accuracy: 98.360002%



# --- The End ---

看看 label 是怎樣？ 不必弄成 one-hot ? --> 不必！ --> 那 prediction 的結果長怎樣呢？ --> 直接就是在 `prediction['probabilities']` array 裡面照 0-9 的順序給出每個 digit 的 probability. 


In [25]:
%f y :> [0] type . cr

<class 'numpy.int32'>


In [17]:
# Make input function for prediction:
#   shuffle=False -> do not randomize input data
pred_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": input(mnist.test)[0]},
    y=input(mnist.test)[1],
    num_epochs=1,
    shuffle=False
    )

In [18]:
# 從 wh300/DNNClassifier_Predicting.ipynb 抄來的例子
# Predict 整批 test input 
preds = classifier.predict(pred_input_fn)

In [19]:
predict = [i for i in preds];

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./tmp/mnist_model\model.ckpt-100000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [20]:
predictions = [int(i['probabilities'][1] > i['probabilities'][0]) for i in predict];

In [21]:
%f predictions py> sum(pop()) tib.
%f y py> sum(pop()) tib.


predictions py> sum(pop()) tib. \ ==> 5646 (<class 'int'>)
y py> sum(pop()) tib. \ ==> 44434 (<class 'numpy.int32'>)


In [23]:
input(mnist.test)[1]

array([7, 2, 1, ..., 4, 5, 6])

In [22]:
predict

[{'class_ids': array([7], dtype=int64),
  'classes': array([b'7'], dtype=object),
  'logits': array([ -9.688227 ,  -3.172889 ,  -2.7975245,  -2.8414974,  -8.5858345,
         -11.756119 ,  -7.365403 ,  16.173954 ,  -9.455394 ,  -5.500797 ],
        dtype=float32),
  'probabilities': array([5.8640497e-12, 3.9607055e-09, 5.7649032e-09, 5.5168905e-09,
         1.7658770e-11, 7.4152110e-13, 5.9839432e-11, 1.0000000e+00,
         7.4014232e-12, 3.8616696e-10], dtype=float32)},
 {'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object),
  'logits': array([ -1.4192035,  -4.685433 ,  18.410631 ,  -0.9773788, -25.717442 ,
          -9.366398 , -13.543909 , -17.782732 ,  -6.215159 , -23.959063 ],
        dtype=float32),
  'probabilities': array([2.4435010e-09, 9.3219557e-11, 1.0000000e+00, 3.8009680e-09,
         6.8457442e-20, 8.6415087e-13, 1.3253162e-14, 1.9117103e-16,
         2.0190889e-11, 3.9726088e-19], dtype=float32)},
 {'class_ids': array([1], dtype=int64),
  'cla